RibonDAO/shared

package.json, rollup.config.js, src/types/apiResponses/IntegrationImpact.ts, tsconfig.json, yarn.lock
Update absolute paths to relative paths when building
This is necessary so the package correctly get the types when being used
=> feat: add absolute to relative path when building

.github/workflows/publish.yml
- Add github action to deploy package to NPM
=> feat: add github action to deploy package to npm

src/config/testUtils/factories/nonProfitFactory.ts, src/config/testUtils/factories/nonProfitImpactFactory.ts, src/types/entities/NonProfit.ts, src/types/entities/NonProfitImpact.ts
- Fix an error from the previous version
=> fix: nonprofit impacts factory and tests

src/lib/impactNormalizer/index.test.ts, src/lib/impactNormalizer/index.ts
Use "for" and "of" connectives when building the impact string
=> fix: use "of" connective when building the impact string

package.json, src/config/index.ts, src/index.ts
=> feat: add config to exports

src/styles/typography/default.ts, src/styles/typography/stylized.ts, src/styles/typography/typography.ts
=> Tech 280: new typography

src/styles/globalStyle.ts, src/styles/normalize.ts, src/styles/theme.ts
=> Tech 298: ds spacing

src/hooks/apiHooks/useCanDonate/index.ts, src/hooks/apiHooks/useCardGivingFees/index.ts, src/hooks/apiHooks/useDonations/index.ts, src/hooks/apiHooks/useImpact/index.ts, src/hooks/apiHooks/useIntegration/index.ts, src/hooks/apiHooks/useIntegrationImpact/index.ts, src/hooks/apiHooks/useNonProfitImpact/index.ts, src/hooks/apiHooks/usePromoterCardGivings/index.ts, src/hooks/apiHooks/useStatistics/index.ts
- Add criteria to some api hooks
=> feat: add criteria to most api hooks

package.json, src/hooks/apiHooks/useCryptoTransaction/index.test.ts, src/hooks/apiHooks/useCryptoTransaction/index.ts, src/services/api/cryptoTransactionsApi/index.test.ts, src/services/api/cryptoTransactionsApi/index.ts, src/types/entities/NonProfit.ts, src/types/enums/Currencies.ts
- Add more types
- Update useCryptoTransaction with new param
=> feat: add more types and useCryptoTransaction new param

src/hooks/apiHooks/useUsers/index.test.ts, src/hooks/apiHooks/useUsers/index.ts, src/services/api/usersApi/index.test.ts, src/services/api/usersApi/index.ts
- Add language param to use users
=> feat: update use users with language attribute

src/types/entities/PersonPayment.ts, src/types/entities/index.ts
=> feat: add PersonPayment

src/hooks/apiHooks/useImpact/index.ts, src/hooks/apiHooks/useStatistics/index.ts
- Update useImpact and useStatistics to return refetch
=> fix: add refetch return to useImpact and useStatistics

src/hooks/index.ts, src/hooks/useApi/queryClient.tsx
=> fix: add exports query clinet

package.json, src/hooks/apiHooks/useStatistics/index.ts, src/services/api/usersApi/index.ts
- Adjust use statistics to receive wallet address to calculate impact
- eg: closes #679
=> [DAPP-679] Adjust use statistics to receive wallet address

src/hooks/apiHooks/useStatistics/index.ts, src/services/api/usersApi/index.ts
- Fix param and add criteria and options
=> fix use statistics

src/hooks/apiHooks/useArticles/index.ts, src/services/api/articlesApi/index.test.ts, src/services/api/articlesApi/index.ts, src/types/entities/Article.ts
- Add sortable parameters to useArticles hook and article services and entities
- Add published at in words
=> feat: add sortable params

src/types/entities/Article.ts
fix: make link optional for articles
=> fix: make link optional for articles

src/types/entities/PersonPayment.ts
=> fix: update guest to crypto_user

src/hooks/apiHooks/useDonations/index.ts, src/services/api/donationsApi/index.ts, src/types/entities/Donation.ts
- Add platform param to donations hook
- eg: closes #DAPP-689
=> [DAPP-689] - Add platform param 

src/types/entities/Notification.ts
- Add new params to notifications type
- eg: closes #DAPP-727
=> [DAPP-727] Add new params to notifications type

src/hooks/apiHooks/useLegacyImpact/index.ts, src/hooks/index.ts, src/services/api/legacyImpactApi/index.test.ts, src/services/api/legacyImpactApi/index.ts, src/services/index.ts, src/types/entities/LegacyNonProfit.ts, src/types/entities/LegacyUserImpact.ts, src/types/entities/index.ts
=> feat: add useLegacyImpact hook

README.md
- Add description to react-native problems and linking locally to the mobile app
=> docs: update readme with react-native problems

src/hooks/apiHooks/useCanDonate/index.ts, src/types/apiResponses/CanDonate.ts, src/types/entities/User.ts
- Add donateApp as param to user
- eg: closes #DAPP-718
=> [DAPP-718] Add donateApp

src/hooks/apiHooks/useTasksStatistics/index.ts, src/hooks/index.ts, src/services/api/usersApi/index.ts, src/types/apiResponses/TasksStatistics.ts
=> feat: add new routes to tasks statistics

src/config/testUtils/factories/nonProfitFactory.ts, src/config/testUtils/factories/storyFactory.ts, src/types/apiResponses/Story.ts, src/types/entities/Cause.ts, src/types/entities/NonProfit.ts, src/types/entities/Story.ts
-  add confirmation to non profit
=> feat: add confirmation to non profit

src/types/entities/LegacyContribution.ts
- Update legacy contribution types
=> fix: update legacy contribution types

src/types/apiResponses/CompletedTask.ts
=> feat: new fields for tasks

src/hooks/apiHooks/useChains/index.ts, src/hooks/index.ts, src/services/api/chainsApi/index.test.ts, src/services/api/chainsApi/index.ts, src/types/entities/Chain.ts, src/types/entities/index.ts
=> Tech 563: Send chains to frontend

src/config/testUtils/factories/nonProfitFactory.ts, src/types/entities/NonProfit.ts
- replace cover image descriprion with logo description
=> fix: replace cover image descriprion with logo description

src/hooks/apiHooks/useUsers/index.test.ts, src/hooks/apiHooks/useUsers/index.ts, src/services/api/usersApi/index.test.ts, src/services/api/usersApi/index.ts
Consumers for sending email and delete an existing user
=> feat: delete user consumers

src/hooks/apiHooks/useUsers/index.test.ts, src/hooks/apiHooks/useUsers/index.ts
Return true only if the request returns 200
=> hotfix: delete response

src/hooks/apiHooks/useFirstAccessIntegration/index.tsx, src/hooks/index.ts, src/services/api/usersApi/index.ts, src/types/apiResponses/FirstAccessToIntegration.ts, src/types/apiResponses/index.ts
- adds firstAccessToIntegration hook
=> feat: dapp-769

src/styles/theme.ts
=> feat: theme icons

src/types/entities/ContributionStats.ts
=> Tech 536: added usagePercentage

src/types/entities/ContributionDirectImpact.ts, src/types/entities/index.ts
- Add ContributionDirectImpact type
=> feat: add ContributionDirectImpact type

src/types/entities/ContributionStats.ts
- Added boost new contributors and new patrons for indirect impact section
=> Tech 545: boost new contributors

src/types/entities/ContributionStats.ts
- Add new fields to contribution stats
=> chore: add new fields to contribution stats

src/hooks/apiHooks/useCanDonate/index.ts, src/hooks/apiHooks/useCryptoTransaction/index.test.ts, src/hooks/apiHooks/useCryptoTransaction/index.ts, src/hooks/apiHooks/useDonations/index.ts, src/services/api/cryptoTransactionsApi/index.test.ts, src/services/api/cryptoTransactionsApi/index.ts, src/services/api/donationsApi/index.ts, src/services/api/usersApi/index.ts, src/types/entities/Donation.ts, src/types/entities/PersonPayment.ts
- add platform to types and requests of crypto and credit card payment
- 
- eg: closes #PROD3-72
=> feat: add platform to types and requests

src/hooks/apiHooks/useCardGivingFees/index.ts, src/services/api/givingFeesApi/index.ts
=> HOTFIX: gateway param

src/hooks/apiHooks/useContributions/index.ts, src/hooks/index.ts, src/services/api/contributionsApi/index.ts
=> feat: add useContributions hook

src/types/entities/Cause.ts
- add pool balance to cause type
- eg: closes #PROD3-77
=> feat: add pool balance to cause type

src/hooks/apiHooks/useCauses/index.ts
=> Prod3-35: disable refetch of causes

src/types/entities/PixPayment.ts, src/types/entities/index.ts
=> feat: add PixPayment type

src/hooks/apiHooks/useNonProfits/index.ts
- add params to not refetch non profits 
- eg: closes #prod-35
=> feat: add params to not refetch non profits

src/hooks/apiHooks/useDonations/index.ts, src/hooks/apiHooks/useSources/index.ts, src/services/api/donationsApi/index.ts, src/services/api/sourcesApi/index.ts
- fix type of integrationId to accept string
- eg: closes #prod3-105
=> fix: type of integrationid

src/hooks/apiHooks/useSubscriptions/index.ts, src/hooks/index.ts, src/services/api/subscriptionApi/index.test.ts, src/services/api/subscriptionApi/index.ts, src/services/index.ts, src/types/entities/Subscription.ts
- Add hook of subscriptions and type to return user subscriptions and cancel subscription request
- eg: closes #prod3-90
=> [PROD3-90] Add useSubscriptions and type

src/hooks/apiHooks/useSubscriptions/index.ts
=> fix: import

src/hooks/apiHooks/useDonations/index.ts
=> Add utm on donation hook

src/hooks/apiHooks/useSubscriptions/index.test.ts, src/hooks/apiHooks/useSubscriptions/index.ts, src/services/api/subscriptionApi/index.test.ts, src/services/api/subscriptionApi/index.ts, src/services/api/usersApi/index.test.ts, src/services/api/usersApi/index.ts
- Update cancel subscription to use token instead of id
=> Feat: update cancel subscription to use token

src/types/apiResponses/NonProfitImpactResponse.ts
- Update NonProfitImpactResponse type
=> feat: update non profit impact response type

src/types/entities/Subscription.ts
- added nextPaymentAttempt on subscription interface
=> feat: added nextPaymentAttempt on subscription interface

src/services/api/articlesApi/index.ts
- Adds e method for getting articles since user creation
- [prod3-127](https://ribon.atlassian.net/browse/PROD3-127?atlOrigin=eyJpIjoiOGQ1YjAxNWUyNjU3NDI0ZjhlMGFlMDE3NWJjNGFjZmYiLCJwIjoiaiJ9)
=> feat: adds articles_since_user_creation request

src/hooks/apiHooks/useDonations/index.ts, src/services/api/impactApi/index.test.ts, src/services/api/impactApi/index.ts, src/types/apiResponses/DonationsCount.ts
=> feat: app donations count

package.json, src/hooks/apiHooks/useArticles/index.ts
=> feat: adds user articles request

src/hooks/apiHooks/useUserConfig/index.ts, src/hooks/index.ts
- Add useUserConfig export
- Fix useUserConfig hook name
=> fix: add useUserConfig export

package.json, src/services/authenticationApi/index.ts, src/utils/constants.ts
=> fix: renames duplicated constant

package.json, src/lib/index.ts, src/services/authenticationApi/index.ts, src/utils/constants.ts
=> fix: constant name

src/hooks/apiHooks/useImpressionCards/index.test.ts, src/hooks/apiHooks/useImpressionCards/index.ts, src/hooks/index.ts, src/services/api/impressionCardsApi/index.test.ts, src/services/api/impressionCardsApi/index.ts, src/services/index.ts, src/types/entities/ImpressionCard.ts, src/types/entities/index.ts
=> feat: impression card consumers

src/hooks/index.ts, src/hooks/userHooks/useUserDonations/index.ts, src/hooks/userHooks/useUserV1Config/index.test.ts, src/hooks/userHooks/useUserV1Config/index.ts, src/hooks/userHooks/useUserV1Donations/index.ts, src/services/user/userConfigApi/index.test.ts, src/services/user/userConfigApi/index.ts, src/services/user/userDonationApi/index.test.ts, src/services/user/userDonationApi/index.ts
-  hook donate and check can donate for logged in users
-  hook config to update allow email marketing attribute
=> feat: hook donate and config for logged in users

src/hooks/userHooks/useUserV1Config/index.ts, src/services/user/userConfigApi/index.ts
- adds getUserConfig
- [X ] New feature (non-breaking change which adds functionality)
=> feat: adds getUserConfig

src/hooks/apiHooks/useUserConfig/index.ts, src/services/api/userConfigApi/index.ts
- adds getUserConfig to the useUserConfig hook
=> feat: prod3-254

src/services/user/userAuthenticationApi/index.ts
- this is necessary to check if the user already received an extra ticket
=> fix: send auth email integration id

src/types/entities/ContributionStats.ts
Adds currentIncreasePercentage to contribution stats in order to replace totalIncreasePercentage
=> feat: adds currentIncreasePercentage to contrStats

src/lib/cookies/index.ts
- added path to persist cookies
=> fix: added path to persist cookies

src/hooks/apiHooks/useTickets/index.ts, src/hooks/index.ts, src/hooks/userHooks/useUserTickets/index.ts, src/services/api/ticketsApi/index.ts, src/services/user/userTicketsApi/index.test.ts, src/services/user/userTicketsApi/index.ts, src/types/entities/UserTickets.ts
- Routes to can collect and collect by integration ticket
- Route to tickets available from user
=> feat: routes to ticket and user tickets

src/services/user/index.ts
- request new token only for web
- the app has its own function
=> fix: request new token only for web

src/hooks/userHooks/useUserTickets/index.ts, src/services/user/userTicketsApi/index.test.ts, src/services/user/userTicketsApi/index.ts
-  adds user donate tickets function
- [X ] New feature (non-breaking change which adds functionality)
=> feat: prod3-268

src/hooks/apiHooks/useTickets/index.ts, src/services/api/ticketsApi/index.ts
=> fix: add platform

src/hooks/apiHooks/useTickets/index.ts, src/services/api/ticketsApi/index.ts
- add colllect and donate by integration to use tickets
=> feat: add collect and donate by integration

src/hooks/apiHooks/useTickets/index.ts, src/lib/cookies/index.ts, src/services/api/ticketsApi/index.ts
- add path to remove cookies 
- make email optional for collect and donate method
=> fix: remove cookies path and collect and donate with email optional

src/hooks/apiHooks/useTickets/index.ts, src/services/api/ticketsApi/index.ts
-  add can collect and collect by external id
- eg: closes #PROD3-411
=> feat: add can collect and collect by external id

src/hooks/apiHooks/useTickets/index.ts, src/services/api/ticketsApi/index.ts
=> feat: tickets available on api v1

src/hooks/userHooks/useUserTickets/index.ts
=> fix: return donate result

src/config/testUtils/factories/promoterCardGivingFactory.ts
=> fix: adds category to offer object

src/hooks/apiHooks/useDonatedToday/index.ts
=> fix: use donated today

.env.example
- add env example
- eg: closes #PROD3-437
=> feat: add env example

src/types/entities/RibonConfig.ts
add ribonClubFeePercentage to ribonConfig
=> feat: adds ribonClubFeePercentage to ribonConfig

src/hooks/apiHooks/useTickets/index.ts
=> fix: collect by integration

src/types/entities/Offer.ts, src/types/entities/Plan.ts, src/types/entities/index.ts
- Adds plan entity 
- Adds plan to Offer
=> feat: adds plan entity

src/hooks/userHooks/useUserTickets/index.ts, src/services/user/userTicketsApi/index.ts, src/types/entities/TicketsToCollect.ts
- Hook to check tickets to collect
- eg: closes #PROD3-364
=> [PROD3-364] Hook to tickets to collect

src/hooks/apiHooks/useTickets/index.ts, src/services/api/ticketsApi/index.ts
- Adds collect by club 
- closes PROD3-420
=> feat: prod3-420

src/hooks/index.ts, src/hooks/userHooks/useUserSubscription/index.ts, src/services/user/userSubscriptionApi/index.test.ts, src/services/user/userSubscriptionApi/index.ts, src/types/apiResponses/IsMember.ts
- Add a hook to return if the user is member of ribon club
=> feat: add is member hook

src/hooks/apiHooks/useTickets/index.ts, src/hooks/userHooks/useUserTickets/index.ts, src/services/api/ticketsApi/index.ts, src/services/user/userSubscriptionApi/index.ts, src/services/user/userTicketsApi/index.ts
=> fix: collect by club api

src/hooks/apiHooks/useSubscriptions/index.ts
-  returns isMember unstructured
=> fix: returns isMember unstructured

src/types/entities/Subscription.ts
- adds personPayments to Subscription entity in order to find payment infos 
=> feat: adds personPayments to Subscription

src/types/entities/index.ts
=> fix: exports Subscription entity

src/types/entities/Integration.ts
Now we're creating integrations from the interface so we need to make its id optional
=> fix: make id optional for integrations

src/types/apiResponses/NonProfitImpactResponse.ts, src/types/entities/NonProfitImpact.ts
adds minimumNumberOfTickets to nonprofits impact types
PS: these types are not being used on the manager related PR I sent, but since this attribute is already on core-api's staging I thought it would be best to already update it
=> feat: adds minimumNumberOfTickets

src/services/user/index.ts
=> feat: adjust function request new token

src/services/user/index.ts
- parsed the data on new request
=> fix: parsed the data on new request

src/hooks/apiHooks/useReports/index.ts, src/hooks/index.ts, src/services/api/reportsApi/index.test.ts, src/services/api/reportsApi/index.ts, src/types/entities/Report.ts
- Add report hook to fetch information from the API
=> Feature/reports [PROD3-510]

src/hooks/index.ts
- adds useCoupons to hooks index (i forgot it on the other PR)
=> fix: adds useCoupons to hooks index

src/types/entities/NonProfit.ts
- Adds the new non profits fields to NonProfit type
=> feat: adds new nonprofit fields

src/services/user/userIntegrationsApi/index.test.ts, src/services/user/userIntegrationsApi/index.ts
- Add branch field to getIntegration because we need this to filter.
=> feat: add params to getintegration

src/types/entities/Coupon.ts, src/types/entities/CouponMessage.ts
- Updates coupon and coupon message type
- no, but it updates prod3-475
=> fat: adds coupon message type

src/hooks/apiHooks/useTickets/index.ts, src/services/api/ticketsApi/index.ts
- can collect by coupon id response
=> fix: can collect by coupon id response

src/config/testUtils/factories/nonProfitFactory.ts, src/types/entities/NonProfit.ts
- add type of icon and icon description on non profits
=> feat: add type of icon on non profits

src/hooks/apiHooks/useTickets/index.test.ts, src/hooks/apiHooks/useTickets/index.ts, src/types/entities/UserTickets.ts
- integration_tickets available
=> prod 599: integration_tickets available

src/hooks/apiHooks/useTickets/index.test.ts, src/hooks/apiHooks/useTickets/index.ts, src/types/entities/UserTickets.ts
=> fix: camel case

src/config/testUtils/factories/tagFactory.ts, src/hooks/apiHooks/useTags/index.test.ts, src/hooks/apiHooks/useTags/index.ts, src/hooks/index.ts, src/services/api/tagsApi/index.test.ts, src/services/api/tagsApi/index.ts, src/types/apiResponses/Tag.ts
- Hooks to list tag
- tests
- eg: closes #PROD3-601
=> [PROD3-601] List of tags

src/types/entities/Integration.ts
- New fields for the integration entity
=> feat: new integration fields

src/types/entities/UserStatistics.ts
- add days donating to user statistics
=> feat: add days donating to user statistics

src/hooks/apiHooks/useSubscriptions/index.ts, src/services/api/subscriptionApi/index.test.ts, src/services/api/subscriptionApi/index.ts, src/types/apiResponses/IsClubMember.ts, src/types/apiResponses/IsMember.ts
- Renames from member to club member
- [PROD3-683](https://ribon.atlassian.net/browse/PROD3-683)
=> feat: renames from member to club member

src/services/user/userAuthenticationApi/index.test.ts, src/services/user/userAuthenticationApi/index.ts
Adds OTP authentication methods
=> feat: new OTP auth method

src/hooks/apiHooks/useSubscriptions/index.ts, src/services/api/subscriptionApi/index.ts, src/types/apiResponses/IsMember.ts
- adds IsMember to maintain compatibility
=> fix: IsMember

src/hooks/userHooks/useUserTickets/index.ts, src/services/user/userTicketsApi/index.ts
- adds collect_by_business hooks
- [#prod3-705](https://ribon.atlassian.net/browse/PROD3-705)
=> feat: adds collect by business hooks

src/types/enums/Categories.ts
=> feat: adds business category

src/services/api/index.ts, src/styles/colors/brand.ts
=> feat: add new colors

src/hooks/apiHooks/useDonations/index.ts, src/services/api/donationsApi/index.test.ts, src/services/api/donationsApi/index.ts, src/types/apiResponses/TotalDonationsToday.ts
Adds the call to the new today donations count route
=> feat: adds the new count route

src/types/entities/User.ts
- Adds company and subscription to user entity 
=> fix: adds company and subscription to user entity

src/hooks/apiHooks/useTickets/index.ts
- add source on key query from get tickets to collect
=> fix: add source on key query from get tickets to collect
